name: Release And Publish on muanual trigger

on:
  watch:
    types: started

jobs:
  build_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: XXX
        run: |
          echo ${{ github.repository }}
